# DataFrame
    - Series가 1차원이었다면 DataFrame은 2차원으로 확대된 버전이다.
    - Excel의 SpreadSheet라고 생각하면 이해하기 쉽다.
    - 2차원 이기 때문에 인덱스가 row, column으로 구성되어 있다
        - row: 각 개별 데이터
        - column: 각 개별의 속성을 의미
    - Data Analysis, Machine Learning에서 Data를 변경하기 위해서 많이 사용된다.

[타이타닉 데이터 셋](https://drive.google.com/file/d/1QC5L7QEnweLQiqizWg7SldLeKoAa8Tme/view?usp=sharing)

In [1]:
import os
import numpy as np
import pandas as pd

base_path = r"D:\kdt_0900_ksh\data_analysis\resource\dataset"
file_name = r"titanic.csv"

file_path = os.path.join(base_path, file_name)

In [3]:
pd.read_csv(file_path).head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## 컬럼의 의미
    - survival: Survival(0 = no; 1 = yes)
    - class: Passenger Class(1 = 1st, 2 = 2nd, 3 = 3rd)
    - name: Name #이름
    - sex: Sex #성별
    - age: Age #나이
    - sibsp: Number of Siblings/Spouses Aboard #동승 형제
    - parch: Number of Parents/Children Aboard #동승 부모,자식
    - ticket: Ticket Number #티켓 번호
    - fare: Passenger Fare
    - cabin: Cabin # 객실번호
    - embarked - Pork of Embarkation(C = Cherbourg; Q = Queenstown, S = Southampthon) # 탑승장소

## 1단계 데이터 파악
- shape: 속성(row, column)
- describe: 통계치 계산 함수(기술 통계량)
- info: 데이터의 타입, 각 컬럼의 개수 출력

In [7]:
titanic_df = pd.read_csv(file_path)

In [8]:
print(titanic_df.shape)

(891, 12)

In [9]:
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [10]:
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [14]:
print(titanic_df.index)

RangeIndex(start=0, stop=891, step=1)

In [15]:
print(titanic_df.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [16]:
len(titanic_df)

891

In [17]:
print(titanic_df.size)

10692

In [18]:
print(titanic_df.ndim)

2

In [20]:
print(titanic_df["Name"])
print(type(titanic_df["Name"]))

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str
<class 'pandas.Series'>

## dict -> DataFrame

In [27]:
data = {"이름": "홍길동", "나이": 20, "주소": "서울시 강남"}
data

# dict 2차원인 index 값을 같이 제공해야한다.
pd.DataFrame(data, index=[0])

    이름  나이      주소
0  홍길동  20  서울시 강남

In [29]:
data2 = {"이름": ["홍길동", "장보고", "이순신"], "나이": [20, 30, 40], "주소": ["서울시 강남", "서울시 종로구", "서울시 관악구"]}
pd.DataFrame(data2, index=[0, 1, 2])

    이름  나이       주소
0  홍길동  20   서울시 강남
1  장보고  30  서울시 종로구
2  이순신  40  서울시 관악구

In [36]:
a = pd.Series(data=["홍길동", 20, "경기도 수원"], index=["이름", "나이", "주소"])
b = pd.Series(data=["장보고", 30, "경기도 분당"], index=["이름", "나이", "주소"])
c = pd.Series(data=["이순신", 40, "경기도 의정부"], index=["이름", "나이", "주소"])

pd.DataFrame([a, b, c])

    이름  나이       주소
0  홍길동  20   경기도 수원
1  장보고  30   경기도 분당
2  이순신  40  경기도 의정부

## 데이터 프레임의 인덱싱

In [38]:
titanic_df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [51]:
print(titanic_df["Name"])
print(type(titanic_df["Name"]))

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str
<class 'pandas.Series'>

## 단일 컬럼 슬라이싱

In [50]:
print(type(titanic_df[["Name"]]))

titanic_df[["Name"]].head(1)

<class 'pandas.DataFrame'>

                      Name
0  Braund, Mr. Owen Harris

## 복수 컬럼 슬라이싱

In [56]:
titanic_df[["Name", "Age"]].head()

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0

## Data Frame 행 슬라이싱

In [55]:
titanic_df[0:3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [58]:
titanic_df[::10].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,NaN,S

## loc, iloc: row 선택

In [63]:
print(type(titanic_df.loc[3]))
titanic_df.loc[3]

<class 'pandas.Series'>

PassengerId                                               4
Survived                                                  1
Pclass                                                    1
Name           Futrelle, Mrs. Jacques Heath (Lily May Peel)
Sex                                                  female
Age                                                    35.0
SibSp                                                     1
Parch                                                     0
Ticket                                               113803
Fare                                                   53.1
Cabin                                                  C123
Embarked                                                  S
Name: 3, dtype: object

In [64]:
titanic_df.iloc[3]

PassengerId                                               4
Survived                                                  1
Pclass                                                    1
Name           Futrelle, Mrs. Jacques Heath (Lily May Peel)
Sex                                                  female
Age                                                    35.0
SibSp                                                     1
Parch                                                     0
Ticket                                               113803
Fare                                                   53.1
Cabin                                                  C123
Embarked                                                  S
Name: 3, dtype: object

In [75]:
titanic_df[::10].iloc[0]
titanic_df[::10].loc[10]

PassengerId                                 11
Survived                                     1
Pclass                                       3
Name           Sandstrom, Miss. Marguerite Rut
Sex                                     female
Age                                        4.0
SibSp                                        1
Parch                                        1
Ticket                                 PP 9549
Fare                                      16.7
Cabin                                       G6
Embarked                                     S
Name: 10, dtype: object

## 다중 행 선택

In [78]:
titanic_df.loc[[1, 600, 800]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
600,601,1,2,"Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...",female,24.0,2,1,243847,27.0000,NaN,S
800,801,0,2,"Ponesell, Mr. Martin",male,34.0,0,0,250647,13.0000,NaN,S

In [79]:
titanic_df[:3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [80]:
titanic_df.loc[:3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [82]:
titanic_df.loc[1]["Name"]

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [83]:
titanic_df.loc[1, "Name"]

'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'

In [89]:
# titanic_df.loc[-1]
titanic_df.iloc[-1]

PassengerId                    891
Survived                         0
Pclass                           3
Name           Dooley, Mr. Patrick
Sex                           male
Age                           32.0
SibSp                            0
Parch                            0
Ticket                      370376
Fare                          7.75
Cabin                          NaN
Embarked                         Q
Name: 890, dtype: object

In [93]:
# 100행의 나이
titanic_df.loc[100, "Age"]
titanic_df.loc[[100]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
100,101,0,3,"Petranec, Miss. Matilda",female,28.0,0,0,349245,7.8958,NaN,S

In [98]:
# 100행의 나이
titanic_df.iloc[100]["Age"]
titanic_df.iloc[[100]]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
100,101,0,3,"Petranec, Miss. Matilda",female,28.0,0,0,349245,7.8958,NaN,S

In [104]:
# 100행의 나이
print(titanic_df[::5].loc[100, "Age"])
titanic_df[::5].loc[[100]]

28.0

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
100,101,0,3,"Petranec, Miss. Matilda",female,28.0,0,0,349245,7.8958,NaN,S

In [102]:
# 100행의 나이
print(titanic_df[::5].iloc[100]["Age"])
titanic_df[::5].iloc[[100]]

17.0

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
500,501,0,3,"Calic, Mr. Petar",male,17.0,0,0,315086,8.6625,NaN,S

In [107]:
titanic_df.loc[[100, 200, 300], ["Name", "Age"]]

                                         Name   Age
100                   Petranec, Miss. Matilda  28.0
200            Vande Walle, Mr. Nestor Cyriel  28.0
300  Kelly, Miss. Anna Katherine "Annie Kate"   NaN

In [109]:
titanic_df.loc[[100, 200, 300]][["Name", "Age"]]

                                         Name   Age
100                   Petranec, Miss. Matilda  28.0
200            Vande Walle, Mr. Nestor Cyriel  28.0
300  Kelly, Miss. Anna Katherine "Annie Kate"   NaN

## Boolean Selection

In [115]:
age_mask = titanic_df["Age"] > 30
len(titanic_df[age_mask])

305

In [117]:
titanic_df.Sex.value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [121]:
hogu_mask = titanic_df["Fare"] > 400
titanic_df[hogu_mask]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C

## 여성의 생존자 조회

In [151]:
titanic_df["Survived"]

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [152]:
titanic_df["Sex"]

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: str

In [132]:
survived_mask = (titanic_df["Survived"] == 1) & (titanic_df["Sex"] == "female")
survived_mask

0      False
1       True
2       True
3       True
4      False
       ...
886    False
887     True
888    False
889    False
890    False
Length: 891, dtype: bool

In [138]:
servived_female = titanic_df[survived_mask]
servived_female.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [140]:
femail = titanic_df[titanic_df["Sex"] == "female"]
len(femail)

314

In [148]:
print(f"생존자 수: {len(servived_female)}명")
print(f"생존율: 약 {round(len(servived_female) / len(femail), 4) * 100}%")

생존자 수: 233명
생존율: 약 74.2%

## 1등석과 3등석의 생존율 비교

In [161]:
survived_mask = titanic_df["Survived"] == 1
titanic_df[survived_mask]

print(f"타이타닉호의 생존률: {len(titanic_df[survived_mask]) / len(titanic_df) * 100:.2f}%")

타이타닉호의 생존률: 38.38%

In [169]:
pclass_1_mask = titanic_df["Pclass"] == 1
pclass_3_mask = titanic_df["Pclass"] == 3

pclass_1_survived = len(titanic_df[survived_mask & pclass_1_mask])
pclass_3_survived = len(titanic_df[survived_mask & pclass_3_mask])

print(f"타이타닉호의 1등석 생존률: {pclass_1_survived / len(titanic_df[pclass_1_mask]) * 100:.2f}%")
print(f"타이타닉호의 3등석 생존률: {pclass_3_survived / len(titanic_df[pclass_3_mask]) * 100:.2f}%")

타이타닉호의 1등석 생존률: 62.96%
타이타닉호의 3등석 생존률: 24.24%

In [174]:
titanic_df.groupby("Pclass")["Survived"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [176]:
titanic_df.groupby("Pclass")["Survived"].agg(["mean", "count"])

            mean  count
Pclass
1       0.629630    216
2       0.472826    184
3       0.242363    491

In [186]:
survived_pclass = titanic_df.groupby("Pclass")["Survived"].mean()

pd.DataFrame(data=survived_pclass * 100, index=[1, 2, 3])

    Survived
1  62.962963
2  47.282609
3  24.236253

In [194]:
survived_pclass = titanic_df.groupby("Pclass")["Survived"].mean()
survived_pclass.index = ["1등석", "2등석", "3등석"]
survived_pclass

pd.DataFrame(data=survived_pclass * 100, index=["1등석", "2등석", "3등석"])

      Survived
1등석  62.962963
2등석  47.282609
3등석  24.236253

## 파생 변수
- 기존에 존재하는 속성(변수, 컬럼)으로 부터 새로운 속성(컬럼)을 만들어낸 변수

In [196]:
# key가 없으면 추가
titanic_df["RealAge"] = titanic_df["Age"] - 1

In [197]:
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,RealAge
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,21.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,37.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,25.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,34.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,34.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,26.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,18.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,25.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,31.0

## 변수 삭제(column 삭제): .drop()
- axis=0(default)-행, 1-열
- inplace=False(default)

In [205]:
# titanic_df.drop("Cabin")
titanic_df.drop("Cabin", axis=1)
titanic_df.drop(["Cabin", "Embarked"], axis=1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,RealAge
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,21.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,37.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,25.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,34.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,34.0
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,26.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,18.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,25.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,31.0

In [206]:
titanic_df.drop(["Cabin", "Embarked"], axis=1, inplace=True)

In [208]:
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,RealAge
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,21.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,37.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,25.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,34.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,34.0
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,26.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,18.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,25.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,31.0

## 파생 변수 만들기 연습

In [210]:
np.nan == np.nan

False

In [228]:
# 만약 NaN이라면: 알수없음
# 19세 이상: 성인
# 19세 미만: 아이
# if ~ elif ~ else
def get_adult(age):
    if np.isnan(age):
        return "알 수 없음"

    return "성인" if age >= 19 else "아이"

get_adult(20)

'성인'

In [232]:
# .apply(): 앞의 시리즈의 값을 순차적으로 받아서 결과를 바꾸고 새로운 결과를 반환하는 함수
titanic_df["IsAdult"] = titanic_df["Age"].apply(get_adult)
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,RealAge,IsAdult
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,21.0,성인
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,37.0,성인
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,25.0,성인
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,34.0,성인
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,34.0,성인
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,26.0,성인
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,18.0,성인
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,알 수 없음
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,25.0,성인
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,31.0,성인

In [235]:
# RipOff
# Fare > 300: 바가지 요금
# Fare <= 300: 정상 요금

titanic_df["RipOff"] = titanic_df["Fare"].apply(lambda fare: "바가지" if fare > 300 else "정상")

In [237]:
titanic_df[titanic_df["Fare"] > 300]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,RealAge,IsAdult,RipOff
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,34.0,성인,바가지
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,35.0,성인,바가지
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,34.0,성인,바가지

In [240]:
# 파생변수 IsAdult, RipOff 두 개를 모두 삭제
titanic_df.drop(["IsAdult", "RipOff"], axis=1, inplace=True)

In [241]:
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,RealAge
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,21.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,37.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,25.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,34.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,34.0
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,26.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,18.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,25.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,31.0