In [27]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.DataFrame({
    "product": ["A", "B", "C", "D", "E", "F", "F"],
    "price": [12000, 15000, np.nan, 18000, 20000, 999999, 999999],
    "stock": [10, 5, 8, np.nan, 20, 3, 3],
    "category": ["식품", "전자", "식품", "전자", np.nan, "식품", "식품"],
    "sold": [5, 2, 7, 1, 9, 3, 3]
})

df

  product     price  stock category  sold
0       A   12000.0   10.0       식품     5
1       B   15000.0    5.0       전자     2
2       C       NaN    8.0       식품     7
3       D   18000.0    NaN       전자     1
4       E   20000.0   20.0      NaN     9
5       F  999999.0    3.0       식품     3
6       F  999999.0    3.0       식품     3

# 1번. 결측치와 중복 데이터 전처리

In [29]:
# 1. 결측치와 중복 데이터 전처리
df.isnull().sum()

product     0
price       1
stock       1
category    1
sold        0
dtype: int64

In [34]:
# 2. price의 결측치를 price의 중앙값으로 대체하시오
df["price"] = df["price"].fillna(df["price"].median())
df

  product     price  stock category  sold
0       A   12000.0   10.0       식품     5
1       B   15000.0    5.0       전자     2
2       C   19000.0    8.0       식품     7
3       D   18000.0    NaN       전자     1
4       E   20000.0   20.0      NaN     9
5       F  999999.0    3.0       식품     3
6       F  999999.0    3.0       식품     3

In [42]:
# 3. stock의 결측치를 stock의 평균값으로 대체하시오.
df["stock"] = df["stock"].fillna(df["stock"].mean())
df

  product     price  stock category  sold
0       A   12000.0   10.0       식품     5
1       B   15000.0    5.0       전자     2
2       C   19000.0    8.0       식품     7
3       D   18000.0    9.2       전자     1
4       E   20000.0   20.0       식품     9
5       F  999999.0    3.0       식품     3

In [37]:
# 4. category의 결측치를 category의 최빈값으로 대체하시오.
df["category"] = df["category"].fillna(df["category"].mode()[0])
df

  product     price  stock category  sold
0       A   12000.0   10.0       식품     5
1       B   15000.0    5.0       전자     2
2       C   19000.0    8.0       식품     7
3       D   18000.0    NaN       전자     1
4       E   20000.0   20.0       식품     9
5       F  999999.0    3.0       식품     3
6       F  999999.0    3.0       식품     3

In [40]:
# 5. 중복된 행 제거
df = df.drop_duplicates()
df

  product     price  stock category  sold
0       A   12000.0   10.0       식품     5
1       B   15000.0    5.0       전자     2
2       C   19000.0    8.0       식품     7
3       D   18000.0    NaN       전자     1
4       E   20000.0   20.0       식품     9
5       F  999999.0    3.0       식품     3

In [45]:
# 6. 인덱스를 0부터 다시 설정하시오.
df = df.reset_index(drop=True)
df

  product     price  stock category  sold
0       A   12000.0   10.0       식품     5
1       B   15000.0    5.0       전자     2
2       C   19000.0    8.0       식품     7
3       D   18000.0    9.2       전자     1
4       E   20000.0   20.0       식품     9
5       F  999999.0    3.0       식품     3

# 2번. 새로운 컬럼 생성 및 조건 필터링

In [47]:
# 1. price * sold 값을 계산하여 revenue 컬럼을 생성하시오.
df["revenue"] = df["price"] * df["sold"]
df

  product     price  stock category  sold    revenue
0       A   12000.0   10.0       식품     5    60000.0
1       B   15000.0    5.0       전자     2    30000.0
2       C   19000.0    8.0       식품     7   133000.0
3       D   18000.0    9.2       전자     1    18000.0
4       E   20000.0   20.0       식품     9   180000.0
5       F  999999.0    3.0       식품     3  2999997.0

In [53]:
# 2. revenue가 100000 이상인 데이터만 high_revenue에 저장하시오.
high_revenue = df[df["revenue"] >= 100000]

In [61]:
# 3. high_revenue를 revenue가 높은 순서대로 정렬하시오.
high_revenue.sort_values("revenue", ascending=False)

  product     price  stock category  sold    revenue  high_revenue
5       F  999999.0    3.0       식품     3  2999997.0          True
4       E   20000.0   20.0       식품     9   180000.0          True
2       C   19000.0    8.0       식품     7   133000.0          True

In [63]:
# 4. product, category, revenue 컬럼만 출력하시오.
df[["product", "category", "revenue"]]

  product category    revenue
0       A       식품    60000.0
1       B       전자    30000.0
2       C       식품   133000.0
3       D       전자    18000.0
4       E       식품   180000.0
5       F       식품  2999997.0